CREATE TABLE [dbo].[DYZUR] (
    [ID_DYZUR] [int] NOT NULL IDENTITY,
    [DZIEN_DYZURU] [datetime] NOT NULL,
    [OD] [datetime] NOT NULL,
    [DO] [datetime] NOT NULL,
    [ID_PRACOWNIK] [int] NOT NULL,
    [ID_ODDZIAL] [int],
    CONSTRAINT [PK_dbo.DYZUR] PRIMARY KEY ([ID_DYZUR])
)
CREATE TABLE [dbo].[ODDZIAL] (
    [ID_ODDZIAL] [int] NOT NULL IDENTITY,
    [NAZWA] [nvarchar](max) NOT NULL,
    [MIEJSCOWOSC] [nvarchar](max) NOT NULL,
    [ID_PLACOWKA] [int] NOT NULL,
    CONSTRAINT [PK_dbo.ODDZIAL] PRIMARY KEY ([ID_ODDZIAL])
)
CREATE TABLE [dbo].[ODDZIAL_PRACOWNIK] (
    [ID_ODDZIAL_PRACOWNIK] [int] NOT NULL IDENTITY,
    [ID_PRACOWNIK] [int] NOT NULL,
    [ID_ODDZIAL] [int] NOT NULL,
    CONSTRAINT [PK_dbo.ODDZIAL_PRACOWNIK] PRIMARY KEY ([ID_ODDZIAL_PRACOWNIK])
)
CREATE TABLE [dbo].[PRACOWNIK] (
    [ID_PRACOWNIK] [int] NOT NULL IDENTITY,
    [IMIE] [nvarchar](max) NOT NULL,
    [NAZWISKO] [nvarchar](max) NOT NULL,
    [ADRES] [nvarchar](max) NOT NULL,
    [EMAIL_KONTAKTOWY] [nvarchar](max),
    CONSTRAINT [PK_dbo.PRACOWNIK] PRIMARY KEY ([ID_PRACOWNIK])
)
CREATE TABLE [dbo].[PRACOWNIK_SPECJALIZACJA] (
    [ID_PRACOWNIK_SPECJALIZACJA] [int] NOT NULL IDENTITY,
    [ID_PRACOWNIK] [int] NOT NULL,
    [ID_SPECJALIZACJA] [int] NOT NULL,
    CONSTRAINT [PK_dbo.PRACOWNIK_SPECJALIZACJA] PRIMARY KEY ([ID_PRACOWNIK_SPECJALIZACJA])
)
CREATE TABLE [dbo].[SPECJALIZACJA] (
    [ID_SPECJALIZACJA] [int] NOT NULL IDENTITY,
    [NAZWA] [nvarchar](max) NOT NULL,
    CONSTRAINT [PK_dbo.SPECJALIZACJA] PRIMARY KEY ([ID_SPECJALIZACJA])
)
CREATE TABLE [dbo].[WIZYTA] (
    [ID_WIZYTA] [int] NOT NULL IDENTITY,
    [DATA_WIZYTY] [datetime] NOT NULL,
    [ID_SALA] [int] NOT NULL,
    [ID_PRACOWNIK] [int] NOT NULL,
    [ID_ODDZIAL] [int] NOT NULL,
    [ID_PACJENT] [int] NOT NULL,
    [ID_RECEPTA] [int],
    [UWAGI] [nvarchar](max),
    CONSTRAINT [PK_dbo.WIZYTA] PRIMARY KEY ([ID_WIZYTA])
)
CREATE TABLE [dbo].[PACJENT] (
    [ID_PACJENT] [int] NOT NULL IDENTITY,
    [IMIE] [nvarchar](max) NOT NULL,
    [NAZWISKO] [nvarchar](max) NOT NULL,
    [ADRES] [nvarchar](max) NOT NULL,
    [PESEL] [bigint] NOT NULL,
    [TELEFON_KONTAKTOWY] [nvarchar](max),
    [EMAIL_KONTAKTOWY] [nvarchar](max),
    CONSTRAINT [PK_dbo.PACJENT] PRIMARY KEY ([ID_PACJENT])
)
CREATE TABLE [dbo].[RECEPTA] (
    [ID_RECEPTA] [int] NOT NULL IDENTITY,
    [DATA_WYKORZYSTANIA] [datetime] NOT NULL,
    [NAZWA_LEKU] [nvarchar](max) NOT NULL,
    [UWAGI] [nvarchar](max),
    CONSTRAINT [PK_dbo.RECEPTA] PRIMARY KEY ([ID_RECEPTA])
)
CREATE TABLE [dbo].[SALA] (
    [ID_SALA] [int] NOT NULL IDENTITY,
    [NUMER_SALI] [int] NOT NULL,
    CONSTRAINT [PK_dbo.SALA] PRIMARY KEY ([ID_SALA])
)
CREATE TABLE [dbo].[PLACOWKA] (
    [ID_PLACOWKA] [int] NOT NULL IDENTITY,
    [NAZWA] [nvarchar](max) NOT NULL,
    [MIEJSCOWOSC] [nvarchar](max) NOT NULL,
    [ADRES] [nvarchar](max) NOT NULL,
    CONSTRAINT [PK_dbo.PLACOWKA] PRIMARY KEY ([ID_PLACOWKA])
)
CREATE INDEX [IX_ID_PRACOWNIK] ON [dbo].[DYZUR]([ID_PRACOWNIK])
CREATE INDEX [IX_ID_ODDZIAL] ON [dbo].[DYZUR]([ID_ODDZIAL])
CREATE INDEX [IX_ID_PLACOWKA] ON [dbo].[ODDZIAL]([ID_PLACOWKA])
CREATE INDEX [IX_ID_PRACOWNIK] ON [dbo].[ODDZIAL_PRACOWNIK]([ID_PRACOWNIK])
CREATE INDEX [IX_ID_ODDZIAL] ON [dbo].[ODDZIAL_PRACOWNIK]([ID_ODDZIAL])
CREATE INDEX [IX_ID_PRACOWNIK] ON [dbo].[PRACOWNIK_SPECJALIZACJA]([ID_PRACOWNIK])
CREATE INDEX [IX_ID_SPECJALIZACJA] ON [dbo].[PRACOWNIK_SPECJALIZACJA]([ID_SPECJALIZACJA])
CREATE INDEX [IX_ID_SALA] ON [dbo].[WIZYTA]([ID_SALA])
CREATE INDEX [IX_ID_PRACOWNIK] ON [dbo].[WIZYTA]([ID_PRACOWNIK])
CREATE INDEX [IX_ID_ODDZIAL] ON [dbo].[WIZYTA]([ID_ODDZIAL])
CREATE INDEX [IX_ID_PACJENT] ON [dbo].[WIZYTA]([ID_PACJENT])
CREATE INDEX [IX_ID_RECEPTA] ON [dbo].[WIZYTA]([ID_RECEPTA])
ALTER TABLE [dbo].[DYZUR] ADD CONSTRAINT [FK_dbo.DYZUR_dbo.ODDZIAL_ID_ODDZIAL] FOREIGN KEY ([ID_ODDZIAL]) REFERENCES [dbo].[ODDZIAL] ([ID_ODDZIAL])
ALTER TABLE [dbo].[DYZUR] ADD CONSTRAINT [FK_dbo.DYZUR_dbo.PRACOWNIK_ID_PRACOWNIK] FOREIGN KEY ([ID_PRACOWNIK]) REFERENCES [dbo].[PRACOWNIK] ([ID_PRACOWNIK]) ON DELETE CASCADE
ALTER TABLE [dbo].[ODDZIAL] ADD CONSTRAINT [FK_dbo.ODDZIAL_dbo.PLACOWKA_ID_PLACOWKA] FOREIGN KEY ([ID_PLACOWKA]) REFERENCES [dbo].[PLACOWKA] ([ID_PLACOWKA]) ON DELETE CASCADE
ALTER TABLE [dbo].[ODDZIAL_PRACOWNIK] ADD CONSTRAINT [FK_dbo.ODDZIAL_PRACOWNIK_dbo.ODDZIAL_ID_ODDZIAL] FOREIGN KEY ([ID_ODDZIAL]) REFERENCES [dbo].[ODDZIAL] ([ID_ODDZIAL]) ON DELETE CASCADE
ALTER TABLE [dbo].[ODDZIAL_PRACOWNIK] ADD CONSTRAINT [FK_dbo.ODDZIAL_PRACOWNIK_dbo.PRACOWNIK_ID_PRACOWNIK] FOREIGN KEY ([ID_PRACOWNIK]) REFERENCES [dbo].[PRACOWNIK] ([ID_PRACOWNIK]) ON DELETE CASCADE
ALTER TABLE [dbo].[PRACOWNIK_SPECJALIZACJA] ADD CONSTRAINT [FK_dbo.PRACOWNIK_SPECJALIZACJA_dbo.PRACOWNIK_ID_PRACOWNIK] FOREIGN KEY ([ID_PRACOWNIK]) REFERENCES [dbo].[PRACOWNIK] ([ID_PRACOWNIK]) ON DELETE CASCADE
ALTER TABLE [dbo].[PRACOWNIK_SPECJALIZACJA] ADD CONSTRAINT [FK_dbo.PRACOWNIK_SPECJALIZACJA_dbo.SPECJALIZACJA_ID_SPECJALIZACJA] FOREIGN KEY ([ID_SPECJALIZACJA]) REFERENCES [dbo].[SPECJALIZACJA] ([ID_SPECJALIZACJA]) ON DELETE CASCADE
ALTER TABLE [dbo].[WIZYTA] ADD CONSTRAINT [FK_dbo.WIZYTA_dbo.ODDZIAL_ID_ODDZIAL] FOREIGN KEY ([ID_ODDZIAL]) REFERENCES [dbo].[ODDZIAL] ([ID_ODDZIAL]) ON DELETE CASCADE
ALTER TABLE [dbo].[WIZYTA] ADD CONSTRAINT [FK_dbo.WIZYTA_dbo.PACJENT_ID_PACJENT] FOREIGN KEY ([ID_PACJENT]) REFERENCES [dbo].[PACJENT] ([ID_PACJENT]) ON DELETE CASCADE
ALTER TABLE [dbo].[WIZYTA] ADD CONSTRAINT [FK_dbo.WIZYTA_dbo.PRACOWNIK_ID_PRACOWNIK] FOREIGN KEY ([ID_PRACOWNIK]) REFERENCES [dbo].[PRACOWNIK] ([ID_PRACOWNIK]) ON DELETE CASCADE
ALTER TABLE [dbo].[WIZYTA] ADD CONSTRAINT [FK_dbo.WIZYTA_dbo.RECEPTA_ID_RECEPTA] FOREIGN KEY ([ID_RECEPTA]) REFERENCES [dbo].[RECEPTA] ([ID_RECEPTA])
ALTER TABLE [dbo].[WIZYTA] ADD CONSTRAINT [FK_dbo.WIZYTA_dbo.SALA_ID_SALA] FOREIGN KEY ([ID_SALA]) REFERENCES [dbo].[SALA] ([ID_SALA]) ON DELETE CASCADE